language: cpp
branches:
  only:
    - master
compiler:
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 clang-3.4 llvm-dev
  - sudo wget $OSX_CROSS_TOOL -O /tmp/osxcross.tgz
  - sudo mkdir -p /tmp/osxcross/target
  - sudo tar xzf /tmp/osxcross.tgz -C /tmp/osxcross/target/
  - export PATH=$PATH:/tmp/osxcross/target/bin
  - wget http://yapb.jeefo.net/ci/scripts/gitrev.sh && chmod +x ./gitrev.sh && ./gitrev.sh
script:
  - cd project && make all
after_success:
  - curl --ftp-create-dirs -T ./release/yapb.so -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/release/yapb.so
  - curl --ftp-create-dirs -T ./debug/yapb.so -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/debug/yapb.so
  - curl --ftp-create-dirs -T ./release/yapb.dylib -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/release/yapb.dylib
  - curl --ftp-create-dirs -T ./debug/yapb.dylib -u $FTP_USER:$FTP_PASS ftp://$FTP_HOST/project/debug/yapb.dylib
